### ISSUE TITLE
Final video is very different from the original one

### ISSUE THREAD

**Issue by idiosyn** [qqgg231/youtube-auto-cc-set-language#1]
The final result is a video much longer than the original one.

The MKVMerge command in the code generates a video that has all the three videos downloaded with YouTube-DL. Notice that in your example (https://www.youtube.com/watch?v=mpr56rFH4UY) there are two videos after the original one: the School of Life video (cc.mkv) and another one (proper_cc.mkv) in a loop.

Is this how it is supposed to work?

**Comment by karolzlot** [comment]
@idiosyn 

Yes, exactly. It is working ok, you just need to upload this result video to Youtube and wait

I noticed that when Youtube checks which language is used in video it checks which language is most common in it.  If original video is incorrectly detetected as German, and should be English, we can just merge it with any video which is a bit longer and is properly detected as English

Loop is needed to extend video to be longer than original one.

I also included "School of Life" video (cc.mkv) to promote them, it can be removed from script without any consequences if you want

----

When you have working auto cc and want your video to be shorter, you can export correct cc somehow from youtube and upload original video with exported subtitles

**Comment by idiosyn** [comment]
Thanks for the answer. I was actually wondering what was the purpose of the School of Life video.

Nice workaround. I did exactly what you suggested (exported correct CC, then used it on original video).

**Comment by karolzlot** [comment]
You are welcome :smile:

If you don't mind please share before and after links and give a star
